# Docs:
# https://aka.ms/yaml

trigger:
  - master
variables:
  serviceConnection: azurerm-demodata
  keyvaultName: cftappsdata-demo
  terraformVersion: 0.12.16
  agentPool: 'Ubuntu-18.04'

stages:
  - stage: CI
    jobs:
      - job: Validate
        pool:
          vmImage: ${{ variables.agentPool }}
        steps:
          - task: PowerShell@2
            displayName: 'Run tests'
            inputs:
              targetType: 'inline'
              script: |
                Install-Module -Name Pester -Force -Verbose -Scope CurrentUser
                Invoke-Pester ./ci -OutputFormat NUnitXml -OutputFile ./TEST-CI.xml -EnableExit
              failOnStderr: true
              pwsh: true
          - task: PublishTestResults@2
            displayName: 'Publish Test Results **/TEST-*.xml'
            inputs:
              testResultsFormat: NUnit
              failTaskOnFailedTests: true
            condition: always()

          - task: TerraformInstaller@0
            inputs:
              terraformVersion: ${{ variables.terraformVersion }}

          - template: devops-templates/terraform-plan-template.yaml
            parameters:
              environment: 'demodata'
              resource_key: 'demodata'
              component: 'demo-api-mgmt-config'
              serviceConnectionName: 'DCD-CFTAPPSDATA-DEMO'

          - task: CopyFiles@2
            displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
            inputs:
              Contents: |
               component/**
              TargetFolder: '$(Build.ArtifactStagingDirectory)'
          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifact: drop'
  - stage: DemoData_Api_Mgmt_Config
    #condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    jobs:
      - template: devops-templates/terraform-apply-template.yaml
        parameters:
          environment: 'demodata'
          agentPool: ${{ variables.agentPool }}
          terraformVersion: ${{ variables.terraformVersion }}
          serviceConnectionName: 'DCD-CFTAPPSDATA-DEMO'
          component: 'demo-api-mgmt-config'